export const ON_LOGIN_ACTION = "ON_LOGIN_ACTION";
export const ON_LOGOUT_ACTION = "ON_LOGOUT_ACTION";

export const ON_GET_USERLIST_ACTION = "ON_GET_USERLIST_ACTION";
export const ON_GET_USER_ACTION = "ON_GET_USER_ACTION";
export const ON_GET_USER_BY_USERNAME_ACTION = "ON_GET_USER_BY_USERNAME_ACTION";
export const ON_UPDATE_USER_ACTION = "ON_UPDATE_USER_ACTION";

export const ON_LOCAL_STORAGE_ACTION = "ON_LOCAL_STORAGE_ACTION";

export const ON_GET_EMAILS_ACTION = "ON_GET_EMAILS_ACTION";
export const ON_GET_DRAFTS_ACTION = "ON_GET_DRAFTS_ACTION";
export const ON_GET_SENT_EMAILS_ACTION = "ON_GET_SENT_EMAILS_ACTION";
export const ON_GET_RECEIVED_EMAILS_ACTION = "ON_GET_RECEIVED_EMAILS_ACTION";
export const ON_GET_EMAIL_ACTION = "ON_GET_EMAIL_ACTION";

export const ON_GET_USER_BY_EMAIL_ACTION = "ON_GET_USER_BY_EMAIL_ACTION";
